package org.au.dynamicflame.model;

// Generated 09/03/2014 6:49:16 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Album generated by hbm2java
 */
@SuppressWarnings("rawtypes")
@Entity
@Table(name = "album", catalog = "dynamicflame")
public class Album implements java.io.Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;
    private Short albumId;
    private String albumName;

    private Set images = new HashSet(0);

    public Album() {}

    public Album(final String albumName, final Set images) {
        this.albumName = albumName;
        this.images = images;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "album_id", unique = true, nullable = false)
    public Short getAlbumId() {
        return albumId;
    }

    public void setAlbumId(final Short albumId) {
        this.albumId = albumId;
    }

    @Column(name = "album_name", length = 45)
    public String getAlbumName() {
        return albumName;
    }

    public void setAlbumName(final String albumName) {
        this.albumName = albumName;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "albums")
    public Set getImages() {
        return images;
    }

    public void setImages(final Set images) {
        this.images = images;
    }

}
