package org.au.dynamicflame.model;

// Generated 09/03/2014 6:49:16 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name = "image", catalog = "dynamicflame")
public class Image implements java.io.Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;
    private Short imageId;
    private String title;
    private String metaType;
    private String location;
    private Date uploadDate;
    private Set<Album> albums = new HashSet<Album>(0);

    public Image() {
    }

    public Image(final String title, final String metaType, final String location, final Date uploadDate) {
        this.title = title;
        this.metaType = metaType;
        this.location = location;
        this.uploadDate = new Date(uploadDate.getTime());
    }

    public Image(final String title, final String metaType, final String location, final Date uploadDate, final Set<Album> albums) {
        this.title = title;
        this.metaType = metaType;
        this.location = location;
        this.uploadDate = new Date(uploadDate.getTime());
        this.albums = albums;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "image_id", unique = true, nullable = false)
    public Short getImageId() {
        return imageId;
    }

    public void setImageId(final Short imageId) {
        this.imageId = imageId;
    }

    @Column(name = "title", nullable = false, length = 45)
    public String getTitle() {
        return title;
    }

    public void setTitle(final String title) {
        this.title = title;
    }

    @Column(name = "meta_type", nullable = false, length = 5)
    public String getMetaType() {
        return metaType;
    }

    public void setMetaType(final String metaType) {
        this.metaType = metaType;
    }

    @Column(name = "location", nullable = false)
    public String getLocation() {
        return location;
    }

    public void setLocation(final String location) {
        this.location = location;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "upload_date", nullable = false, length = 19)
    public Date getUploadDate() {
        return uploadDate;
    }

    public void setUploadDate(final Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    @ManyToMany(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @JoinTable(name = "image_album", catalog = "dynamicflame", joinColumns = { @JoinColumn(name = "image_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "album_id", nullable = false, updatable = false) })
    public Set<Album> getAlbums() {
        return albums;
    }

    public void setAlbums(final Set<Album> albums) {
        this.albums = albums;
    }

}
